modLoader="javafml"
loaderVersion="[24,)"

issueTrackerURL="https://github.com/MrCrayfish/GlassCutter/issues"

[[mods]]
modId="glasscutter"
version="1.0.1"
displayName="Glasscutter"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/glasscutter/update.json"
displayURL="https://mrcrayfish.com/mods?id=glasscutter"
logoFile=""
credits="@DarkestArgentum on Twitter for ideas"
authors="MrCrayfish"
description='Adds a glasscutter to cut different shapes with glass'

[[dependencies.glasscutter]]
    modId="forge"
    mandatory=true
    versionRange="[24,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.glasscutter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.4.4,1.16)"
    ordering="NONE"
    side="BOTH"
